services:
  - type: web
    name: php-mvc-app
    env: php
    rootDir: public
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_HOST
        fromService:
          name: mysql-db
          type: pserv
      - key: DB_NAME
        value: your_db_name
      - key: DB_USER
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password

databases:
  - name: mysql-db
    databaseName: your_db_name
    user: your_db_user
